# Generated by Django 4.2.27 on 2026-02-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_companydetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetails',
            options={'verbose_name': 'Company Details', 'verbose_name_plural': 'Company Details'},
        ),
        migrations.AddField(
            model_name='companydetails',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
