# Generated by Django 4.2.27 on 2026-02-09 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_type', 'name']},
        ),
    ]
